/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { useSignIn, useUser } from "@clerk/nextjs";
import { zodResolver } from "@hookform/resolvers/zod";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { Button } from "~/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "~/components/ui/form";
import { Input } from "~/components/ui/input";

const formSchema = z.object({
  username: z.string().min(2, {
    message: "Username must be at least 2 characters.",
  }),
  password: z.string().min(8, {
    message: "Password must be at least 8 characters.",
  }),
});

export default function SignIn() {
  const { isSignedIn } = useUser();
  const router = useRouter();

  if (isSignedIn) {
    router.push("/");
  }

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      username: "",
      password: "",
    },
  });

  const { isLoaded, signIn, setActive } = useSignIn();

  if (!isLoaded) {
    return null;
  }

  async function onSubmit(values: z.infer<typeof formSchema>) {
    if (signIn) {
      await signIn
        .create({
          identifier: values.username,
          password: values.password,
        })
        .then((result) => {
          if (result.status === "complete") {
            setActive({ session: result.createdSessionId });
            router.push("/");
          }
        })
        .catch((err) =>
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          console.error("error", err.errors[0].longMessage),
        );
    }
  }

  return (
    <>
      <Head>
        <title>DevLinks - Signin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8">
        <Image
          src="/images/logo-devlinks-large.svg"
          alt="devlinks logo"
          width={183}
          height={40}
          className="cursor-pointer"
          onClick={() => router.push("/")}
        />
        <h3 className="mt-16">Login</h3>
        <p className="mt-2 text-[#737373]">
          Add your details below to get back into the app
        </p>
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="mt-10 space-y-6"
          >
            <FormField
              control={form.control}
              name="username"
              render={({ field }) => (
                <FormItem className="space-y-1">
                  <FormLabel>
                    <h6>Username</h6>
                  </FormLabel>
                  <FormControl>
                    <Input placeholder="e.g. alex@email.com" {...field} />
                  </FormControl>

                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="password"
              render={({ field }) => (
                <FormItem className="space-y-1">
                  <FormLabel>
                    <h6>Password</h6>
                  </FormLabel>
                  <FormControl>
                    <Input
                      placeholder="Enter your password"
                      {...field}
                      type="password"
                      autoComplete="on"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="flex flex-col items-center">
              <Button
                type="submit"
                className="font-instrument w-full bg-[#633CFF] font-bold text-white hover:bg-[#BEADFF]"
              >
                Submit
              </Button>
              <h5 className="mt-6 text-[#737373]">
                Don&apos;t have an account?
              </h5>
              <Link href="/sign-up">
                <h5 className="text-[#633CFF]">Create account</h5>
              </Link>
            </div>
          </form>
        </Form>
      </main>
    </>
  );
}
