/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { useSignIn, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";

export default function SignIn() {
  const { isSignedIn } = useUser();
  const router = useRouter();

  if (isSignedIn) {
    router.push("/");
  }

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const { isLoaded, signIn, setActive } = useSignIn();

  if (!isLoaded) {
    return null;
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (signIn) {
      await signIn
        .create({
          identifier: email,
          password,
        })
        .then((result) => {
          if (result.status === "complete") {
            console.log(result);
            setActive({ session: result.createdSessionId });
            router.push("/");
          } else {
            console.log(result);
          }
        })
        .catch((err) =>
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          console.error("error", err.errors[0].longMessage),
        );
    }
  }

  return (
    <>
      <Head>
        <title>DevLinks - Signin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8">
        <Image
          src="/images/logo-devlinks-large.svg"
          alt="devlinks logo"
          width={183}
          height={40}
        />
        <h3 className="mt-16">Login</h3>
        <p className="mt-2 text-[#737373]">
          Add your details below to get back into the app
        </p>
        <form onSubmit={submit} className="mt-10 space-y-6">
          <div>
            <label htmlFor="email">
              <h6>Email address</h6>
            </label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="e.g. alex@email.com"
              className="placeholder:font-instrument mt-1 w-full rounded-md border p-2"
            />
          </div>
          <div>
            <label htmlFor="password">
              <h6>Password</h6>
            </label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Enter your password"
              className="placeholder:font-instrument mt-1 w-full rounded-md border p-2"
            />
          </div>
          <div className="flex flex-col items-center">
            <button className="w-full rounded-md bg-[#633CFF] px-[27px] py-[11px]">
              <h4 className="text-white">Login</h4>
            </button>
            <h5 className="mt-6 text-[#737373]">Don&apos;t have an account?</h5>
            <Link href="/sign-up">
              <h5 className="text-[#633CFF]">Create account</h5>
            </Link>
          </div>
        </form>
      </main>
    </>
  );
}
