import Head from "next/head";
import EditLinks from "~/components/edit/edit-links";
import MainHeader from "~/components/header/main/main-header";
import { api } from "~/utils/api";

export default function EditLinksPage() {
  const { data, isLoading } = api.profile.getProfile.useQuery();

  if (!data || isLoading) {
    return;
  }

  return (
    <>
      <Head>
        <title>DevLinks - Edit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader data={data} />
      <EditLinks data={data} />
    </>
  );
}
