import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import CustomizeLinks from "~/components/edit/customize-links";
import PhonePreview from "~/components/edit/phone-preview";
import Header from "~/components/header/header";

export default function EditLinksPage() {
  const { isLoaded, isSignedIn, user } = useUser();

  if (!isLoaded || !isSignedIn) {
    return null;
  }
  return (
    <>
      <Head>
        <title>DevLinks - Edit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="bg-[#FAFAFA] p-4 md:p-6 md:pt-0 lg:flex lg:gap-6">
        <PhonePreview />
        <CustomizeLinks userId={user.id} />
      </main>
    </>
  );
}
