import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import EditProfile from "~/components/edit/edit-profile";
import MainHeader from "~/components/header/main/main-header";
import { api } from "~/utils/api";

export default function EditProfilePage() {
  const { isLoaded, isSignedIn, user } = useUser();

  if (!isLoaded || !isSignedIn) {
    return null;
  }

  const { data, isLoading } = api.profile.getProfile.useQuery({
    userId: user.id,
  });

  return (
    <>
      <Head>
        <title>DevLinks - Edit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader data={data} isLoading={isLoading} />
      <EditProfile data={data} isLoading={isLoading} />
    </>
  );
}
