/* eslint-disable @typescript-eslint/no-floating-promises */
import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import AuthCard from "~/components/auth/auth-card";
import SignUpForm from "~/components/auth/sign-up-form/form/sign-up-form";
import VerificationForm from "~/components/auth/sign-up-form/form/verification-form";

export default function SignUpPage() {
  const { isSignedIn } = useUser();
  const router = useRouter();
  const [pendingVerification, setPendingVerification] = useState(false);
  const [email, setEmail] = useState<string | undefined>();

  if (isSignedIn) {
    router.push("/edit/links");
  }

  return (
    <>
      <Head>
        <title>DevLinks - Signup</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthCard>
        {!pendingVerification && (
          <SignUpForm
            setPendingVerification={setPendingVerification}
            setEmail={setEmail}
          />
        )}
        {pendingVerification && email && <VerificationForm email={email} />}
      </AuthCard>
    </>
  );
}
