import { UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const { isLoaded, isSignedIn, user } = useUser();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="absolute right-4 top-4">
          {user ? (
            <UserButton afterSignOutUrl="/" />
          ) : (
            <>
              {/* <SignUpButton /> */}
              <Link href="/sign-in/">Login</Link>
            </>
          )}
        </div>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Devlinks</span> Landing
            Page
          </h1>

          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          {isLoaded && isSignedIn && (
            <p className="text-2xl font-thin text-white">
              Hello{" "}
              <span className="font-semibold">
                {user.primaryEmailAddress?.emailAddress ?? user.firstName}
              </span>{" "}
              welcome to Clerk
            </p>
          )}
        </div>
      </main>
    </>
  );
}
